#!/usr/bin/env bash
set -eu
shift # remove -o
exe_file=$1
work_dir=$2

for f in ${work_dir}/*.s
do
  o=${f%\.s}.o
  as -o $o $f
done

# Note: I tried mold, but there wasn't any difference in linking time. Probably because the program is too small ?
ld -o ${exe_file} ${work_dir}/*.o
