#!/usr/bin/env bash
# ./bld2 -o outfile compiler pkgdir
set -eux
shift
outfile=$1
compiler=$2
pkgdir=$3

workdir=${compiler}.d
export WORKDIR=$workdir
mkdir -p $workdir
$compiler list -deps $pkgdir  > $workdir/list
cat  $workdir/list | ./build.sh -o $outfile $compiler $pkgdir
