#!/usr/bin/env bash
set -ex
compiler=$1
workdir=$2
shift
shift

rm -rf $workdir
mkdir -p $workdir

if [[ $(uname) == "Darwin" ]] ; then
  compiler=./${compiler}
fi

WORKDIR="$workdir" $compiler "$@"

cd $workdir
cat *.s > all
