#!/usr/bin/env bash
set -e
shift # remove -o
workdir=$1
compiler=$2
shift
shift

rm -rf $workdir
mkdir -p $workdir

if [[ $(uname) == "Darwin" ]] ; then
  compiler=./${compiler}
fi

echo WORKDIR="$workdir" $compiler "$@"
WORKDIR="$workdir" $compiler "$@"

cd $workdir
cat *.s > all
