#!/usr/bin/env bash
# Usage:
#    ./docker-run   enter into container with bash
#    ./docker-run <command> run a command in the container

if [[ $# -eq 1 ]]; then
  cmd="bash"
else
  cmd="$@"
fi

docker run -it --rm \
    --name bbg \
    -w /root/go/src/github.com/DQNEO/babygo\
    -v `pwd`:/root/go/src/github.com/DQNEO/babygo\
    --cap-add=SYS_PTRACE\
    --security-opt='seccomp=unconfined'\
    --env GOPATH=/root/go \
    --env tmp=/tmpfs/bbg \
    --tmpfs=/tmpfs:rw,exec,size=500m,mode=1777 \
    --tmpfs=/root/go/src/github.com/DQNEO/babygo/tmp:rw,size=500m,mode=1777\
     dqneo/ubuntu-compiler-go $cmd

# Change prompt in the container
# export PS1='docker:\W $ '
