#!/usr/bin/env bash
# Usage:
#   go-build -o outfile -c compiler [package]
#
####
set -eu
REPO_ROOT=$(cd $(dirname $0);pwd)

shift # skip -o
out_file=$1
shift # skip -c
compiler=$2
package=$3

out_file_abs=$(realpath $out_file)
workdir=${out_file}.d
export WORKDIR=$workdir
mkdir -p $workdir
$compiler list -deps $package  > $workdir/list

PKGS=""
while read p
do
  if [[ $p == "main" ]]; then
    continue
  fi
  PKGS="$PKGS $p"
  p2=$(echo $p | tr '/' '.')
  $compiler compile -o $workdir/$p2  $p
done < $workdir/list

# Compile main
$compiler compile -o $workdir/main $package

cd $workdir

# Assemble .s files
for a in *.s
do
  b=${a%*.s}
  as $a -o ${b}.o
done


# Generate __INIT__.s
{
cat <<EOF
.text
# Initializes all packages except for runtime
.global __INIT__.init
__INIT__.init:
EOF

PKGSM="${PKGS} main"
for p in $PKGSM
do
  if [[ $p == "runtime" ]] ; then
      continue
  fi
  p2=$(echo $p | tr '/' '.')
  basename=${p##*/}
  echo "  callq ${basename}.__initVars"
  if grep -E '^func init' ${p2}.dcl.go >/dev/null ; then
    echo "  callq ${basename}.init"
  fi
done
echo "  ret"
} > __INIT__.s

# Link
as -o __INIT__.o __INIT__.s
ld -o a.out *.o
cp a.out $out_file_abs

cat *.s > all
echo $out_file
