#!/usr/bin/env bash
# Usage:
#   go-build -o outfile -c prog [package]
#
####
set -eu
REPO_ROOT=$(cd $(dirname $0);pwd)
verbose=""
if [[ $1 == "-x" ]]; then
  verbose="1"
  shift
fi

tmp=${tmp:=/tmp/bbg}

shift # skip -o
out_file=$1
shift # skip -c
prog=$2
package=$3

out_file_abs=$(realpath $out_file)
workdir=${tmp}/${out_file##*/}.d
export WORKDIR=$workdir

echo WORKDIR=$workdir $prog build -o $out_file $package
$prog build -o $out_file $package

# Generate __INIT__.s
{
cat <<EOF
.text
# Initializes all packages except for runtime
.global __INIT__.init
__INIT__.init:
EOF

while read p
do
  if [[ $p == "runtime" ]] ; then
      continue
  fi
  p2=$(echo $p | tr '/' '.')
  basename=${p##*/}
  echo "  callq ${basename}.__initVars"
  if grep -E '^func init' $workdir/${p2}.dcl.go >/dev/null ; then
    echo "  callq ${basename}.init"
  fi
done < $workdir/list

echo "  ret"
} > $workdir/__INIT__.s

as -o $workdir/__INIT__.o $workdir/__INIT__.s

cd $workdir


# Link
if [[ -n $verbose ]]; then
  echo '>' $prog link -o $out_file_abs *.o
fi
$prog link -o $out_file_abs *.o


cat *.s > all
echo $out_file
