# build from Mac OS
tmp = .shared

.PHONY: test

test: $(tmp)/pre-test.d $(tmp)/bbg-test.d

pre.mac: pre/*.go lib/*/*
	go build -o pre.mac ./pre

babygo.mac: *.go lib/*/* src/*/*
	go build -o babygo.mac .

$(tmp)/pre-test.d: ./pre.mac t/*.go src/*/* lib/*/*
	./compile $< $@ t/*.go

$(tmp)/bbg-test.d: ./bbg.mac t/*.go src/*/* lib/*/*
	./compile $< $@ t/*.go


.PHONY: clean
clean:
	rm -rf ./pre.mac ./babygo.mac $(tmp)/*.d
