name: Test

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go

      - name: Test
        run: GOPATH=/home/runner/work/babygo/babygo  make -C ./src/github.com/DQNEO/babygo test
